# Encoding: UTF-8

name             'my-dev-machine'
maintainer       'Jonathan Hartman'
maintainer_email 'j@p4nt5.com'
license          'apache2'
description      'Installs/Configures my-dev-machine'
long_description 'Installs/Configures my-dev-machine'
version          '0.0.1'

depends          'chef-client', '~> 4.3'
depends          'mac_os_x', '~> 1.4'
depends          'chef-dk', '~> 3.0'
depends          'homebrew', '~> 2.0'
depends          'mac-app-store', '~> 1.0'
depends          'knock', '~> 0.1'
depends          'iwork', '~> 0.1'
depends          'divvy', '~> 0.2'
depends          'microsoft-remote-desktop', '~> 1.0'
depends          'tweetbot', '~> 1.0'
depends          'fantastical', '~> 0.1'
depends          'gimp', '~> 1.0'
depends          'iterm2', '~> 1.4'
depends          'kindle', '~> 0.1'
depends          'dropbox', '~> 0.1'
depends          'box-sync', '~> 1.0'
depends          'private-internet-access', '~> 0.1'
depends          'plex-home-theater', '~> 1.0'
depends          'skype-app', '~> 0.1'
depends          'spotify', '~> 0.1'
depends          'steam', '~> 1.0'
depends          'vlc', '~> 0.1'
depends          'vmware-fusion', '~> 1.0'
depends          'parallels', '~> 0.1'
depends          'webhook', '~> 0.1'
depends          'x2go-client', '~> 0.2'

supports         'mac_os_x'
