# encoding: utf-8
# frozen_string_literal: true

name 'my-dev-machine'
maintainer 'Jonathan Hartman'
maintainer_email 'j@p4nt5.com'
license 'apache2'
description 'Installs/Configures my-dev-machine'
long_description 'Installs/Configures my-dev-machine'
version '0.0.1'

source_url 'https://github.com/roboticcheese/my-dev-machine-chef'
issues_url 'https://github.com/roboticcheese/my-dev-machine-chef/issues'

depends 'build-essential', '~> 8.0'
depends 'chef-client', '~> 7.2'
depends 'mac_os_x', '~> 1.4'
# depends 'chef-dk', '~> 3.0'
depends 'homebrew', '~> 3.0'
depends 'mac-app-store', '~> 3.0'
# depends 'iwork', '~> 1.0'
# depends 'microsoft-remote-desktop', '~> 1.2'
# depends 'tweetbot', '~> 1.1'
# depends 'fantastical', '~> 1.0'
# depends 'gimp', '~> 1.0'
# depends 'iterm2', '~> 1.4'
# depends 'kindle', '~> 1.0'
# depends 'dropbox', '~> 0.1'
# depends 'box-sync', '~> 1.0'
# depends 'private-internet-access', '~> 0.1'
# depends 'plex-home-theater', '~> 1.0'
# depends 'skype-app', '~> 0.1'
# depends 'spotify', '~> 1.0'
# depends 'steam', '~> 2.1'
# depends 'vlc', '~> 1.0'
# depends 'vmware-fusion', '~> 1.0'
# depends 'parallels', '~> 0.1'
# depends 'x2go-client', '~> 1.0'
depends 'dmg', '~> 3.0'

supports 'mac_os_x'
